1. ## TensorFlow Installation
2. **Purpose**: Installs the TensorFlow library, providing the necessary tools for machine learning.

In [1]:
!pip install tensorflow


3. **Explanation**: This command ensures that the Google Colab environment has TensorFlow, a powerful open-source machine learning framework, ready for use in building and training models.

1. ## Importing TensorFlow
2. **Purpose**: Makes the TensorFlow library available for use.

In [2]:
import tensorflow as tf


3. **Explanation**: The `import tensorflow as tf` statement brings the TensorFlow library into your Python environment, aliasing it as `tf`. This convention simplifies referencing TensorFlow functions, such as `tf.constant`, throughout your code.

1. ## Checking TensorFlow Version
2. **Purpose**: Displays the currently installed TensorFlow version.

In [3]:
print(tf.__version__)

2.20.0



3. **Explanation**: Printing `tf.__version__` helps confirm which specific version of TensorFlow is active in the environment. This is crucial for compatibility and debugging, as different versions may have varying features or syntax.

1. ## Creating a Scalar Tensor
2. **Purpose**: Defines a basic, single-value tensor.

In [4]:
# Scalar Value
x_tensor=tf.constant(6)
print(x_tensor)

tf.Tensor(6, shape=(), dtype=int32)



3. **Explanation**: A scalar tensor, like `x_tensor = tf.constant(6)`, holds a single numerical value. In TensorFlow, all data is represented as tensors, and a scalar is a 0-dimensional tensor, indicated by `shape=()` in its output.

1. ## Scalar Tensor Addition (Printed)
2. **Purpose**: Demonstrates basic arithmetic on a scalar tensor.

In [5]:
y_tensor=x_tensor + 10
print(y_tensor)

tf.Tensor(16, shape=(), dtype=int32)



3. **Explanation**: This cell shows how to perform an element-wise addition operation. When `x_tensor` (which holds 6) is added to 10, TensorFlow automatically creates a new scalar tensor `y_tensor` with the resulting value (16), and `print()` explicitly displays it.

1. ## Scalar Tensor Addition (Displayed)
2. **Purpose**: Shows the implicit display of a tensor in Colab.

In [6]:
y_tensor=x_tensor + 10
y_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=16>


3. **Explanation**: Like the previous cell, this performs `x_tensor + 10`. The key difference is that by placing `y_tensor` as the last expression in the cell, Colab's rich output automatically displays the tensor's full details (value, shape, data type) without needing an explicit `print()` statement.

1. ## Direct Tensor Expression Output
2. **Purpose**: Illustrates immediate output of a tensor expression.

In [7]:
x_tensor + 10

<tf.Tensor: shape=(), dtype=int32, numpy=16>


3. **Explanation**: This cell directly evaluates `x_tensor + 10` and, because it's the final expression in the cell, Google Colab automatically displays the resulting tensor's value, shape, and data type, even without assigning it to a variable or explicitly calling `print()`.

1. ## Tensors of Different Ranks
2. **Purpose**: Demonstrates the creation of tensors with varying dimensions.

In [8]:
import tensorflow as tf

# 0D Tensor (scalar)
t0 = tf.constant(7)

# 1D Tensor (vector)
t1 = tf.constant([1, 2, 3])

# 2D Tensor (matrix)
t2 = tf.constant([[1, 2],
                  [3, 4]])

# 3D Tensor (cube / stack of matrices)
t3 = tf.constant([[[1],[2]], [[3],[4]]])

print(t0.shape, t1.shape, t2.shape, t3.shape)


() (3,) (2, 2) (2, 2, 1)




3. **Explanation**: This cell creates and showcases tensors of different ranks (dimensions):
    - **0D Tensor (Scalar)**: `t0` (single value).
    - **1D Tensor (Vector)**: `t1` (sequence).
    - **2D Tensor (Matrix)**: `t2` (grid).
    - **3D Tensor**: `t3` (stack of matrices).
   The `print(t0.shape, ...)` output clearly illustrates how the `.shape` attribute indicates the dimensionality of each tensor.

1. ## Initializing 2D Tensors
2. **Purpose**: Sets up two 2x2 matrices for tensor operations.

In [9]:
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

y = tf.constant([[10.0, 20.0],
                 [30.0, 40.0]])




3. **Explanation**: This cell defines two new 2-dimensional tensors, `x` and `y`, which are essentially 2x2 matrices containing floating-point numbers. These tensors serve as inputs for exploring various arithmetic and manipulation operations in the following cells.

1. ## Element-wise Tensor Operations
2. **Purpose**: Performs basic arithmetic on tensors, element by element.

In [10]:


# Element-wise operations
print("Add:\n", x + y)
print("Multiply:\n", x * y)
print("Subtract:\n", x - y)


Add:
 tf.Tensor(
[[11. 22.]
 [33. 44.]], shape=(2, 2), dtype=float32)
Multiply:
 tf.Tensor(
[[ 10.  40.]
 [ 90. 160.]], shape=(2, 2), dtype=float32)
Subtract:
 tf.Tensor(
[[ -9. -18.]
 [-27. -36.]], shape=(2, 2), dtype=float32)



3. **Explanation**: This cell demonstrates element-wise addition, multiplication, and subtraction between tensors `x` and `y`. In these operations, corresponding elements from each tensor are combined individually, resulting in a new tensor of the same shape where each element is the result of the operation on its respective inputs.

1. ## Matrix Multiplication
2. **Purpose**: Executes the fundamental linear algebra operation of matrix multiplication.

In [11]:

# Matrix multiplication
print("MatMul:\n", tf.matmul(x, y))


MatMul:
 tf.Tensor(
[[ 70. 100.]
 [150. 220.]], shape=(2, 2), dtype=float32)



3. **Explanation**: Unlike element-wise operations, `tf.matmul(x, y)` performs true matrix multiplication. This operation is crucial in many machine learning algorithms. The result is a new matrix where each element is computed by taking the dot product of a row from the first matrix (`x`) and a column from the second matrix (`y`).

1. ## Tensor Reductions and Reshaping
2. **Purpose**: Illustrates how to aggregate tensor data and change its structural dimensions.

In [12]:

# Reductions
print("Sum:", tf.reduce_sum(x))
print("Mean:", tf.reduce_mean(x))

# Reshape
print("Reshape:\n", tf.reshape(x, (4,)))


Sum: tf.Tensor(10.0, shape=(), dtype=float32)
Mean: tf.Tensor(2.5, shape=(), dtype=float32)
Reshape:
 tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)



3. **Explanation**: This cell explores two key tensor manipulations:
    - **Reductions**: `tf.reduce_sum()` and `tf.reduce_mean()` compute aggregate statistics (sum, average) across all elements of a tensor, reducing its dimensionality to a scalar.
    - **Reshaping**: `tf.reshape(x, (4,))` modifies the tensor's shape from a 2x2 matrix to a 1D vector of 4 elements. This operation reinterprets the tensor's elements into a new arrangement without altering the underlying data.

1. ## Simple Linear Regression with Gradient Descent
2. **Purpose**: Implements a basic machine learning model to find a linear relationship in data.

In [13]:
import tensorflow as tf

# Training data (X=inputs, y=targets)
X = tf.constant([[2.0], [4.0], [6.0], [8.0]])
y = tf.constant([[4.0], [8.0], [12.0], [16.0]])

# Trainable parameters (weights & bias)
w = tf.Variable(0.0)
b = tf.Variable(0.0)

lr = 0.01
epochs = 200

for epoch in range(epochs):
    with tf.GradientTape() as tape:
        y_pred = X * w + b
        loss = tf.reduce_mean((y - y_pred)**2)

    dw, db = tape.gradient(loss, [w, b])

    w.assign_sub(lr * dw)
    b.assign_sub(lr * db)

    if epoch % 40 == 0:
        print(f"Epoch {epoch}, Loss={loss.numpy():.4f}, w={w.numpy():.4f}, b={b.numpy():.4f}")

print("\nFinal parameters:")
print("w =", w.numpy(), " b =", b.numpy())
print("Prediction for X=10:", (10*w + b).numpy())


Epoch 0, Loss=120.0000, w=1.2000, b=0.2000
Epoch 40, Loss=0.0137, w=1.9522, b=0.2853
Epoch 80, Loss=0.0105, w=1.9580, b=0.2506
Epoch 120, Loss=0.0081, w=1.9631, b=0.2201
Epoch 160, Loss=0.0063, w=1.9676, b=0.1932

Final parameters:
w = 1.971471  b = 0.17024893
Prediction for X=10: 19.884958



3. **Explanation**: This cell demonstrates a simple linear regression model using TensorFlow. It defines input `X` and target `y` data, then iteratively adjusts `w` (weight) and `b` (bias) using **gradient descent** to minimize the prediction error (loss). A `tf.GradientTape` automatically calculates the gradients needed to update `w` and `b`, guiding the model towards the best fit. Finally, it shows the optimized parameters and a prediction for a new input.